swagger: '2.0'
info:
  title: "E-commerce API"
  description: "API to manage ecommerce interactions"
  version: "1.0.0"
host: "127.0.0.1:5000" #working on local host
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
securityDefinitions:
  bearerAuth:
    type: apiKey ##api key is a built-in authorization for swagger. Yes, we use token auth which is slightly different. However, it works the same way where they pass in a bearer token, or a bearer key. In the same exact way we would pass in our bearer token. That's why they don't have 2 separate ones. The API key works the same as token auth.
    name: Authorization
    in: header
    
paths:

  /customers/login:
    post: #Type of request
      tags:
        - Customers #what category this request belongs to
      summary: "Login Endpoint (generates token)"
      description: "Endpoint for user authentication, and token generaton"
      parameters:
        - in: "body" #payload comes through the body of the request
          name: "body"
          description: "Credentials for login"
          required: true
          schema:
            $ref: "#/definitions/LoginPayload"
      responses:
        200:
          description: "Login Successful"
          schema:
            $ref: "#/definitions/LoginResponse"
          examples:
            application/json:
              auth_token: "sdalkghlsg;sdglfkh...."
              message: "Successfully logged In"
              status: "Success"
  
  /customers:
    get:
      tags:
        - Customers
      summary: "Returns all customers"
      description: "Returns all customers's information (requires token)"
      security:
        - bearerAuth: []
      responses:
        200:
          description: "Retrieve customers successfully"
          schema:
            $ref: "#/definitions/AllCustomers"

  /products:
    get:
      tags:
        - Products
      summary: "Returns all products"
      description: "Returns all products's information (requires token)"
      responses:
        200:
          description: "Retrieve products successfully"
          schema:
            $ref: "#/definitions/AllProducts"

definitions:
  LoginPayload:
    type: "object"
    properties:
      username:
        type: "string"
        description: "customer's username"
      password:
        type: "string"
        description: "customer's password"
    required:
      - "username"
      - "password"

  LoginResponse:
    type: "object"
    properties:
      auth_token:
        type: "string"
        description: "Authorization token"
      message:
        type: "string"
        description: "Successfull logged In"
      status:
        type: "string"
        description: "Success"

  AllCustomers:
    type: "object"
    properties:
      name:
        type: "string"
        description: "Customer's name"
      email:
        type: "string"
        description: "Customer's email"
      phone:
        type: "string"
        description: "Customer's phone number"
      username:
        type: "string"
        description: "Customer's username"
      role_id:
        type: "integer"
        description: "Customer's role id"
  
  AllProducts:
    type: "object"
    properties:
      name:
        type: "string"
        description: "Product's name"
      price:
        type: "float"
        description: "Product's price"