name: Flask CI/CD

on:
  push:
    branches: [main, master] #Setting on Push to main branch, run our jobs


jobs: #The things we want to happen on push

  build:
    runs-on: ubuntu-latest #Ubuntu is a widely used linux distribution that is heavily support and has alot of prebuilt Github actions

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.9 #setting up python on our build environment

      - name: Install libpq-dev
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev
        
      - name: Create vertual Environment
        run: |
          python -m venv venv
          source venv/bin/activate
      - name: Install our Dependecies
        run: |
          python -m pip install --upgrade pip 
          python -m pip install -r requirements.txt
      - name: Print debugging information
        run: |
          echo "Python Version: $(python --version)"
          echo "Working Directory: $(pwd)"
          echo "Content of Working Directory: $(ls-l)"
          echo "Contents of site-package: $(ls -l venv/lib/python*/site-packages)"
  test:
    needs: build
    runs-on: ubuntu-latest #Ubuntu is a widely used linux distribution that is heavily support and has alot of prebuilt Github actions

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.9 #setting up python on our build environment

      - name: Create vertual Environment
        run: |
          python -m venv venv
          source venv/bin/activate
      - name: Install our Dependecies
        run: |
          python -m pip install --upgrade pip 
          python -m pip install -r requirements.txt
      - name: Run test
        run: python -m unittest discover -s tests -p 'test_*.py'

  deploy:
    needs: test
    runs-on: ubuntu-latest #Ubuntu is a widely used linux distribution that is heavily support and has alot of prebuilt Github actions

    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy the App
        env:
            deploy_url: ${{secrets.RENDER_DEPLOY_HOOK_URL}}
        run: curl "$deploy_url"